# Generated by Django 2.1.3 on 2018-11-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField()),
                ('keywords', models.CharField(max_length=64)),
                ('enterChannel', models.CharField(max_length=24)),
                ('scanDuration', models.SmallIntegerField()),
                ('talk', models.SmallIntegerField()),
                ('shoppingCnt', models.SmallIntegerField()),
                ('orderCnt', models.SmallIntegerField()),
                ('price', models.FloatField()),
                ('charges', models.FloatField()),
                ('memo', models.TextField()),
                ('salary', models.FloatField()),
                ('finishStatus', models.SmallIntegerField()),
                ('moneyReturnStatus', models.SmallIntegerField()),
                ('exception', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.CharField(max_length=40)),
                ('shopName', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('shopType', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField()),
                ('itemLink', models.URLField()),
                ('itemName', models.CharField(max_length=64)),
                ('itemCode', models.CharField(max_length=12)),
                ('remark', models.TextField()),
                ('requirements', models.TextField()),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering_info.ShopInfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='itemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering_info.ShopOrder'),
        ),
    ]
